### ISSUE TITLE
Not returning error when index clash

### ISSUE THREAD

**Issue by gabriellanata** [OpenKitten/MongoKitten#71] opened 2016-12-08 17:37 UTC
When a collection has a unique index and I try to add an object which would clash with an existing object, MongoKitten does not throw an error, but the object is not added.

**Steps to reproduce:**

1. Create a database with a unique index on a field (in the example it is field "value")
```
{
  "unique": true,
  "key": { "value": 1 }
}
```

2. Add an object with value "A"
```
let document: MongoKitten.Document = [
      "value": "A"
]
try MongoManager.database["tests"].insert(document)
```

3. Verify document was inserted
```
[{"value":"A","_id":"bb964958d7260b8fbaf1a0e8"}]
```

4. Add a second object with value "A"
```
let document: MongoKitten.Document = [
      "value": "A"
]
try MongoManager.database["tests"].insert(document)
```

5. Verify document was inserted (fails, only original document exists, but no error thrown by MongoKitten)
```
[{"value":"A","_id":"bb964958d7260b8fbaf1a0e8"}]
```

**Other details**

If this same steps are done directly in mongo an error is returned as expected.

**Comment by Joannis** [comment] 2016-12-10 11:47
I'll be investigating this soon. I've got my hands full at the moment.

**Comment by lgaches** [comment] 2017-01-12 09:56
I've added a test for this issue. It passed, I close the issue.

**Comment by clmntcrl** [comment] 2018-09-21 10:51
I currently encounter the same issue with MongoKitten 4:

```swift
let collection = mongo["user"]
try collection.createIndex(named: "username", withParameters: .text(["username"]), .unique)
try collection.insert([ "username": "aaaa" ])
try collection.insert([ "username": "aaaa" ])
```

Only the first insertion is done but there is no error thrown on the second insertion.

**Comment by Joannis** [comment] 2018-09-21 10:53
@clmntcrl does the entity exist? I'm suspecting the index has had trouble along the way or MongoDB doesn't show an error to MongoKitten. The index would be a fault in MongoKitten, the latter would be a detail of MongoKitten/MongoDB. MongoKitten only passes MongoDB errors through, so if you insert 5 entities and 4 succeed, the write concern dictates whether it's an error or not

**Comment by clmntcrl** [comment] 2018-09-21 11:44
All inserts return a unique ObjectId but only the first call successfully insert entity in the mongo collection (because there is no user with "aaaa" username).

**Comment by Joannis** [comment] 2018-09-21 11:50
That's sensible, then my best guess is that you'll want a different WriteConcern

**Comment by clmntcrl** [comment] 2018-09-21 11:56
If I do the same thing directly in MongoDB, the following error is returned:

```
WriteResult({
	"nInserted" : 0,
	"writeError" : {
		"code" : 11000,
		"errmsg" : "E11000 duplicate key error collection: words.User index: username dup key: { : \"aaaa\", : 1.1 }"
	}
})
```

So MongoKitten should also receive an error from MongoDB ?

**Comment by Joannis** [comment] 2018-09-21 11:56
Yeah, I'd think MongoKitten would be throwing an error, too. Just your above code should be able to reproduce this, right?

**Comment by clmntcrl** [comment] 2018-09-21 12:01
Yes

**Comment by Joannis** [comment] 2018-09-21 12:02
I'm not sure then why this isn't working on your end, because the exact same code behaves as expected. I ran your lines of code and I got the expected error

**Comment by clmntcrl** [comment] 2018-09-21 12:16
This is really strange. I use a separate database, drop the collection before launching my test, ... 

```
import Vapor
import MongoKitten

public func boot(_ app: Application) throws {
    let testMongoDataBase = try MongoKitten.Database("mongodb://localhost:27017/testUnique")
    let collection = testMongoDataBase["user"]
    try collection.createIndex(named: "username", withParameters: .text(["username"]), .unique)
    do {
        try collection.insert([ "username": "aaaa" ])
        try collection.insert([ "username": "aaaa" ])
    }
    catch { print(error) }
}
```

**Comment by Joannis** [comment] 2018-09-21 12:20
What version of MongoDB (the server) are you using?

**Comment by clmntcrl** [comment] 2018-09-21 12:39
Placing some breakpoint in MongoKitten code I have find that `CollectionQueryable.insert(documents: ordered: writeConcern:, timeout:, connection: ) throws -> [BSON.Primitive]` well receive the error from MongoDB:

```
ServerReply(requestID: 891, responseTo: 3, flags: MongoKitten.ReplyFlags(rawValue: 8), cursorID: 0, startingFrom: 0, numbersReturned: 1, documents: [{"n":0,"ok":1.0,"writeErrors":[{"index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: testUnique.user index: username dup key: { : \"aaaa\", : 1.1 }"}]}])
```

but the following test prevent the error to be thrown:

```swift
guard Int(reply.documents.first?["ok"]) == 1 else {
    throw throwErrors()
}
```

**Comment by Joannis** [comment] 2018-09-21 12:40
Ahah, that makes sense. So then why is `ok` equal to `1` on your end and not on mine?

**Comment by Joannis** [comment] 2018-09-21 12:42
I'll send you a mention via github here when I have a better idea

**Comment by clmntcrl** [comment] 2018-09-21 12:43
Ok, thanks ;)

**Comment by Joannis** [comment] 2018-09-22 16:27
https://github.com/mongodb/specifications/blob/master/source/command-monitoring/command-monitoring.rst#succeeded-or-failed

There is a nuance though, MongoKitten 4 seems to be correctly behaving here. Although I get that the result is unexpected.

**Comment by clmntcrl** [comment] 2018-09-24 07:48
IMHO you have already answer to the question of multi-document insertion [here](https://github.com/OpenKitten/MongoKitten/issues/101#issuecomment-288015412) on issue #101.

**Comment by Joannis** [comment] 2018-09-24 14:49
I agree, although there's a bit of a problem with the possibility of this change breaking other people's codebases.

**Comment by Joannis** [comment] 2018-09-28 06:36
Ping @Obbut

**Comment by clmntcrl** [comment] 2018-10-30 09:30
Hey @Joannis, @Obbut anything new on this topic?

**Comment by Joannis** [comment] 2018-10-30 09:37
Yeah. We discussed it a few weeks ago, but we didn't come to a solid conclusion yet. According to MongoDB spec the command _is_ successful, but one or more writes were not. So the question we have to ask ourselves is the definition of failure. Is a command failure considered a failure? If that's so, almost every command will _not_ be a failure. If we consider the (un-)successful execution of a part of the query to be indivative of a failure that's another story. Or both. 

In MK5 we have a separation between high and low-level APIs, so this is easier to take care of in the API. If you want the raw results, the low level API is for you. Otherwise we'll make assumptions. 

For MK4 I would like to fix it, but I'm still concerned other people their codebases will break. @Obbut what do you think?

**Comment by clmntcrl** [comment] 2018-10-30 09:59
Thanks. This is a good thing that you have exposed low level API in MK5, I think this is the best option to be sure to don't break things for other people.

**Closed** 2019-03-22 17:25 UTC
Labels: bug
