### ISSUE TITLE
MyApp(22717,0x70000b073000) malloc: *** error for object 0x1545024f0: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug

### ISSUE THREAD

**Issue by raomshauty** [OpenKitten/MongoKitten#135] opened 2017-09-06 05:01 UTC
MyApp(22717,0x70000b073000) malloc: *** error for object 0x1545024f0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

This happens in the attached highlighted line of code inside Socket.swift on line 281.

This only happens when I kick off many simultaneous threads inside an operation queue.  If I only do one at a time I do not see this.

The query I am doing is not instant but its also not terribly heavy (many 2-5 second queries of limit 2000)

This is on latest master.

![screen shot 2017-09-05 at 10 00 49 pm](https://user-images.githubusercontent.com/20232370/30095173-c044690e-9285-11e7-8f00-400add321a99.png)

**Comment by Joannis** [comment] 2017-09-06 11:29
Thanks for reporting! Is it possible for you to provide a reproducible example?

**Comment by raomshauty** [comment] 2017-09-06 21:59
Thank you for your help, here is the code.

The matchingQuery is a wrapper class that contains the values of limit, batch size, and skip params I have built a UI to select from.

What the code does:

- establish connection
- create operation queue using max procs -- (note -- one thing to throw into the mix here is I have a 12-core mac pro, very fast.  And this is currently reproducing doing 4 queries at the same time.  It is of note that my coworker isnt seeing this and hes on a 2 core (4 proc) macbook pro)
- for each different query i want to do, add an operation queue that does queries of the desired limit in batches.  within each queue operation, it is doing the query batches syncronously.
- error sometimes occurs immediately, sometimes never, and sometimes somewhere in the middle.

            let db = try MongoKitten.Database(MONGO_URL, maxConnectionsPerServer: 20000)
            
            let queue = OperationQueue()
            queue.maxConcurrentOperationCount = ProcessInfo.processInfo.activeProcessorCount
            
            for matchingQuery in mongoMatchingQueries {
                
                print("Kicking off query async: \(matchingQuery.friendlyName)")
                
                queue.addOperation {
                    
                    print("Executing query async: \(matchingQuery.friendlyName)")
                    
                    let zoomCollection = db["myCollection"]
                    let projection = matchingQuery.projection
                    var batchSize = matchingQuery.batchSize
                    var skipSize = matchingQuery.skipSize
                    
                    var numMongoQueries = Int(Double(limit) / Double(batchSize))
                    
                    var recordsForThisQuery: [Document] = []
                    
                    for i in 0 ..< numMongoQueries {
                        
                        print("Executing a query batch (size: \(batchSize). batch: \(i)/\(numMongoQueries)) for: \(matchingQuery.friendlyName)")
                        
                        do {
                            
                            let skipping = skipSize + (i * batchSize)
                            
                            for doc in try zoomCollection.find(
                                Query(matchingQuery.query),
                                projecting: projection,
                                skipping: skipping,
                                limitedTo: batchSize,
                                withBatchSize: batchSize
                            )
                            {
                                recordsForThisQuery.append(doc)
                            }
                            
                            print("Finished a query batch (size: \(batchSize). batch: \(i)/\(numMongoQueries)) for: \(matchingQuery.friendlyName)")
                            
                        }
                        catch let error {
                            print("error \(error)")
                            print("mongo error")
                        }
                        
                    }
                    
                    print("Done with query batch")
                    
                }
            }
            
            print("All queries kicked off, now waiting for completion...")
            
            queue.waitUntilAllOperationsAreFinished()
            
            print("All queries complete, calling back out...")

**Comment by raomshauty** [comment] 2017-09-06 22:13
Also, FWIW when it crashes there are a ton of threads in and around the reserveConnection function.

**Comment by raomshauty** [comment] 2017-09-09 01:04
Let me know if you'd like any more information or to try anything...  Currently lots of performance to be gained if I could parallelize this.

**Comment by Joannis** [comment] 2017-09-10 13:52
Sorry for the late replies. This is an insanely tough problem to "patch". It requires a tough rewrite of the connection pool I had planned for MongoKitten 5.

**Comment by raomshauty** [comment] 2017-09-10 19:02
No worries, so you're able to repro then?  Is there anything else you need from me and/or is there any hacky workaround that you know of?

**Comment by Joannis** [comment] 2017-09-10 21:10
It's an issue that's been on my radar for longer, only now it's really concrete where and what the issue is.

The "workaround" isn't really hacky. Limit the maximum amount of connections more. 5-20 should be more than enough. This will reserve up to the limitation in connections. Each connection can do (off the top of my mind) 10 simultaneous requests per connection by default. If you want more concurrency per thread you can easily up it. Some drivers do their processing on 1 thread/connection exclusively. I think 20-100 requests should be doable, too. 

`server.maxActionsPerConnection` or `database.server.maxActionsPerConnection` is in control of this.

**Comment by Joannis** [comment] 2017-11-28 10:45
MongoKitten 5 will rework connections, as stated previously. This is no longer an issue. MongoKitten 5 is being designed with asynchronous programming in mind. I'll close this issue.

**Closed by Joannis** 2017-11-28 10:45 UTC
Labels: bug
