### ISSUE TITLE
Value of type 'UnsafePointer<Any>' has no member 'reversed'

### ISSUE THREAD

**Issue by natebirkholz** [OpenKitten/MongoKitten#160] opened 2018-03-30 22:48 UTC
Using the brand new XCode Version 9.3 (9E145):

In CRUD.swift, in `func insert(documents:ordered:writeConcern:timeout:connection:)`, inside the nested `func throwErrors()` I am getting the error "Value of type 'UnsafePointer<Any>' has no member 'reversed'" on the line `for position in positions.reversed()`

It seems that the compiler is having trouble inferring the correct value type for that line, which looks to be `Array<InsertErrors.InsertError>` and not `UnsafePointer<Any>`

This issue has been seen before in the earlier, now-closed issue https://github.com/OpenKitten/MongoKitten/issues/101

Any workarounds or changes I can make? I just installed MongoKitten today after updating my XCode, so i don't know if this is traceable to the new XCode 9.3/Swift 4.1 or not.

**Comment by Joannis** [comment] 2018-04-01 17:04
It was already fixed and tagged, but the tag was marked as 4.0.17 instead of 4.1.2 
CC @Obbut

**Comment by fruitcoder** [comment] 2018-04-02 09:16
In addition I get a "Command failed due to signal: Abort trap: 6" during compilation of QueryBuilder. The module is included as a dependency of MongoProvider and I'm using the newest Swift 4.1 dev snapshot

**Comment by Joannis** [comment] 2018-04-02 09:24
That's correct, that issue was also originating from a small bit of Swift compiler regression. It seems to be unable to figure out unwrapping two different double-unwraps of enum cases with the same wrapped types.

**Comment by Joannis** [comment] 2018-04-02 09:25
Which MongoKitten version is downloaded locally?

**Comment by fruitcoder** [comment] 2018-04-02 14:05
4.0.17

**Comment by natebirkholz** [comment] 2018-04-02 14:37
I get 4.1.2 currently.

**Comment by fruitcoder** [comment] 2018-04-02 22:22
Weird, I'm getting it trough MongoDriver (dependency of MongoProvider) 
<img width="154" alt="screen shot 2018-04-03 at 00 20 25" src="https://user-images.githubusercontent.com/5515849/38219244-047e9966-36d5-11e8-9b09-4057dc31d680.png">

**Comment by Joannis** [comment] 2018-04-02 23:16
Try updating, I just pushed a new version that should resolve this issue.

**Comment by fruitcoder** [comment] 2018-04-03 09:25
It still fetches 4.0.17 (`vapor fetch`)  :(

**Comment by Joannis** [comment] 2018-04-03 10:20
Try `vapor update` instead

**Comment by Obbut** [comment] 2018-04-03 10:43
As far as I know, MongoDriver has not been upgraded to MongoKitten 4.1, and its Package.swift still lists `.Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 4, minor: 0),`

**Comment by fruitcoder** [comment] 2018-04-03 10:47
Thanks @Joannis. I now have 4.0.19 (@Obbut works because it's not 4.1.*)

**Comment by natebirkholz** [comment] 2018-04-03 14:44
`vapor update` fetches 4.1.3 which fixes the issue, thanks @Joannis

**Comment by Joannis** [comment] 2018-04-13 14:37
@lauren2020 please update to 4.1.3

**Closed** 2018-09-22 16:34 UTC
