### ISSUE TITLE
Connect works without a running MongoDB server

### ISSUE THREAD

**Issue by darkermatter** [OpenKitten/MongoKitten#58] opened 2016-10-28 09:41 UTC
I'm more or less using the code from the tutorial:

``` swift
let server: MongoKitten.Server!

do {
  server = try MongoKitten.Server(hostname: "localhost", port: 27017, automatically: true)
} catch {
  print("eep!")
  fatalError("Can't connect to MongoDB")
}
```

As a test I stopped the MondoDB server:

```
$ telnet localhost 27017
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

The app runs fine and just hangs when trying to insert a document into a collection. I looked at the source of Server.swift (bearing in mind that I only started using Swift yesterday) and the connect() method looks weird so I can't debug it.

**Comment by Joannis** [comment] 2016-10-29 09:50
Ah.. I see. So MongoKitten's Server will initialize without the other end actually running. The reason we allow this to happen is because the biggest use case scenario for this driver is server applications. So let's say if you lose connection with MongoDB for whatever reason you wouldn't want your server application to crash because of it. You'd want to throw `500` internal server errors until it comes back up.

I will however add a method for checking if the connection is alive. I'll get back to you on that.

**Comment by darkermatter** [comment] 2016-10-30 15:33
So, how do I throw a 500 if I can't catch the connection problem in the first place? Then later, the code which actually tries to write to the database just hangs.

**Comment by Joannis** [comment] 2016-10-31 07:46
You're completely right, sorry about that! I'm going to look into a way to solve this which might be difficult and take some time.

**Comment by Joannis** [comment] 2016-10-31 07:52
Which MongoKitten version are you running by the way?

**Comment by darkermatter** [comment] 2016-10-31 07:54
url: https://github.com/OpenKitten/MongoKitten.git", majorVersion: 2, minor: 0

**Comment by Joannis** [comment] 2016-10-31 08:12
When you're executing a command/query on the database, are you being thrown any error? Or none at all?

The part where MongoKitten keeps running when MongoDB goes offline is not a bug, it's a feature.
If you restart MongoDB or have a small connection issue I think it's better to keep attempting to reconnect.

**Comment by darkermatter** [comment] 2016-10-31 08:13
I'll do a couple of tests and let you know

**Comment by darkermatter** [comment] 2016-10-31 09:26
With the MongoDB server running, everything was fine with the document insertion. I then stopped MongoDB and tried again and the request timed out after about 30 seconds with this:
```
Uncaught Error: MongoError.timeout. Use middleware to catch this error and provide a better response. Otherwise, a 500 error page will be returned in the production environment.
```
I then restarted MongoDB and refreshed the insert url. The page still timed out. So, the feature you mention is working as expected :-(

Perhaps ```automatically: true``` could also be accompanied by ```reconnect: true``` which will trigger the connect method in queries and inserts if there is no socket connected?

**Comment by darkermatter** [comment] 2016-10-31 09:27
Maybe ```automatically: true``` could also mean both

**Comment by Joannis** [comment] 2016-10-31 17:27
@darkermatter I'm going to remove the `automatically` as it doesn't *really* serve a useful purpose right now.

If you'd like I can add a method to validate the availability of the server.

**Comment by quen2404** [comment] 2016-11-09 00:30
I have the same problem, my mongo server is down and i set `automatically` to true, but the constructor doesn't raise an exception...

**Comment by Joannis** [comment] 2016-11-13 09:43
This is fixed in MongoKitten 3 by the use of the new `Database` initializer. I'll probably backport this soon.

**Comment by quen2404** [comment] 2016-11-13 21:57
An idea about release date of MongoKitten 3 ?

**Comment by Joannis** [comment] 2016-11-14 13:24
Either wednesday or the end of next week's sunday. I can't work on MongoKitten between wednesday and next week. It all depends on how much I'm able to work on it the next two days, but I don't think I'll make wednesday honestly.

For now you can enjoy almost every feature by updating your Package.swift for "3.0.0-alpha"

`.Package(url: "https://github.com/OpenKitten/MongoKitten.git", "3.0.0-alpha")`

Since I'm unable to work on MongoKitten until the release is near you can expect the code to remain stable almost entirely.

The docs however aren't updated for MongoKitten 3. So if you decide to hop in you'll have to ask me here or on Slack how you'll manage updating your code. It's changing huge parts of the API.

**Closed** 2016-12-10 11:48 UTC
