### ISSUE TITLE
auth issue

### ISSUE THREAD

**Issue by mboeddeker** [OpenKitten/MongoKitten#100] opened 2017-03-14 19:25 UTC
always the same error. i can't authorize into my database. so i'm using a mongurl ("mongodb://username:password@hostname:port")

I checked my username & password with Robomongo and other tools, mongoose and so on, everything works fine.

And please update your link for the Quickstart in the docs!!

**Comment by Joannis** [comment] 2017-03-15 08:05
I've addressed the broken links issue.

As for the authentication tot he database, what version of MongoKitten are you running currently? What MongoDB version are you trying to connect to? Do you know if you're using SCRAM_SHA_1, MONGODB-CR or another mechanism?

**Comment by Joannis** [comment] 2017-03-20 10:22
Has this been resolved?

**Comment by Joannis** [comment] 2017-04-04 10:16
I'll be closing the issue. if the issue is still there, please do re-open it.

**Closed by Joannis** 2017-04-04 10:16 UTC
