### ISSUE TITLE
disconnect() doesn't disconnect

### ISSUE THREAD

**Issue by CocoaPriest** [OpenKitten/MongoKitten#86] opened 2017-01-18 16:45 UTC
I'm very new to the mongodb world, so excuse me if I'm wrong. disconnect() doesn't seem to drop the connection properly for me. In logs I see the connection counter increase with every init, but it's not freed again. 
In the same function, I tried another swift mongodb library (Perfect-MongoDB) and it works as expected there.
Any ideas?

**Comment by Joannis** [comment] 2017-01-18 22:21
In MongoKitten 3, disconnect clears up the connection pool. If you use MongoKitten after that it'll automatically reconnect again. Maybe this is unexpected behaviour.

MongoKitten 2 didn't have a proper connection pool and had `disconnect` as an empty function since it was accidentally not removed when developing it.

MongoKitten 1 did have disconnect implemented because it only had a single connection to the server.


If you're using MongoKitten 2, you're right, it's useless, but removing it would break the API. If you're using MongoKitten 3 then that's either because it's unexpected behaviour to automatically reconnect or a bug. In both cases I'm open to discussing how it should work.

MongoKitten 3 doesn't automatically close connections, which could be added if there's interest and a good argument to need/want that.

**Comment by Joannis** [comment] 2017-01-26 16:24
Assuming you're running 3.0 we did notice an issue like this just now and we'll have it fixed in 3.1.

**Closed by Joannis** 2017-01-26 16:24 UTC
